name: Django Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run Tests
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        cd backend
        python manage.py test
    
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        echo "Add your deployment commands here"
        # Example for deploying to Heroku:
        # git subtree push --prefix backend heroku main
